### ISSUE TITLE
AS A: Gamer I WANT: to be able to create a profile of my gaming interests and preferences SO THAT:  I can have games recommended to me that align with my profile.

### ISSUE THREAD

**Issue by Lileu** [Lileu/SC_200#2]
AS A: Gamer
I WANT: to be able to create a profile of my gaming interests and preferences
SO THAT:  I can have games recommended to me that align with my profile.

Acceptance criteria:
- [ ] Profile module should display when user first logs 

- [ ]  Profile module should have the below fields and validations:

**Comment by Bluesamyou** [comment]
This is very good Lisa. Let us build on this

**Comment by Lileu** [comment]
@Bluesamyou please do the assignment. Thanks in advance.

**Comment by Lileu** [comment]
duplicate item.
